# Generated by Django 4.2.21 on 2025-05-14 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('prof', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReasonForVisit',
            fields=[
                ('reason_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_id', models.AutoField(primary_key=True, serialize=False)),
                ('study_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorlist.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorlist.patient')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorlist.reasonforvisit')),
            ],
        ),
        migrations.CreateModel(
            name='PatientStudy',
            fields=[
                ('patientstudy_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_performed', models.DateField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorlist.patient')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorlist.study')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCard',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('bload', models.CharField(max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorlist.patient')),
            ],
        ),
    ]
